run:
  timeout: 5m
  concurrency: 8
  build-tags:
    - integration
  modules-download-mode: readonly

linters:
  enable:
    # Bug Prevention & Security
    # - errcheck       # Unchecked errors (crashes/data loss)
    - errorlint      # Enforce errors.Is/As instead of == comparison
    - gosec          # Security vulnerabilities
    - govet          # Suspicious constructs
    - staticcheck    # Comprehensive static analysis
    - typecheck      # Type errors
    - bidichk        # Dangerous unicode characters

    # Style & Conventions
    # - revive         # Style and naming conventions
    # - gosimple       # Go idioms
    # # - gocritic       # Comprehensive checks (mixed receivers, performance, etc.)
    # - gofmt          # Standard formatting
    # - goimports      # Import organization

    # Code Quality
    # - unused         # Dead code
    # - ineffassign    # Wasted assignments
    # - dupl           # Code duplication
    # - unconvert      # Unnecessary type conversions
    # - unparam        # Unused function parameters
    # - nakedret       # Naked returns in long functions
    # - nilerr         # Suspicious nil error returns
    # - predeclared    # Shadows predeclared identifiers

    # Resource Leak Detection (Critical for library code)
    - bodyclose      # HTTP response bodies must be closed
    - sqlclosecheck  # SQL rows/statements must be closed
    - noctx          # HTTP requests must use context

    # Complexity
    # - gocyclo        # Cyclomatic complexity
    # - nestif         # Deeply nested if statements

    # Custom Rules
    - forbidigo      # Forbid specific function calls



linters-settings:
  errorlint:
    errorf: true
    asserts: true
    comparison: true

  forbidigo:
    forbid:
      - p: ^os\.Getenv$
        msg: "Use config package instead of os.Getenv"

  gocyclo:
    min-complexity: 15

  # gosec:
  #   severity: medium
  #   confidence: medium
  #   excludes:
  #     - G104  # Covered by errcheck
  #   exclude-generated: true

  revive:
    rules:
      - name: exported
        severity: warning
      - name: package-comments
        severity: warning
      - name: var-naming
        severity: warning

  gocritic:
    enabled-tags:
      - diagnostic
      - style
      - performance
    disabled-checks:
      - commentedOutCode
      - whyNoLint
      - unnamedResult

  nakedret:
    max-func-lines: 30

  unparam:
    check-exported: false  # Don't check exported functions (public API)

  dupl:
    threshold: 100

  nestif:
    min-complexity: 5

issues:
  max-issues-per-linter: 0
  max-same-issues: 0

  exclude-dirs:
    - database/sqlc
    - docs

  exclude-files:
    - ".*\\.pb\\.go$"

  exclude-rules:
    # Test files - relax rules
    - path: _test\.go
      linters:
        - gosec
        - dupl
        - gocyclo
        - unparam
        - bodyclose
        - noctx

    # Generated code - exclude all
    - path: database/sqlc/
      linters:
        - all

    - path: docs/
      linters:
        - all

    - path: database/migrations/
      linters:
        - all

    # Allow fmt.Print in CLI
    - path: cmd/
      linters:
        - forbidigo
      text: "fmt\\.Print"

    # Allow os.Getenv in config package
    - path: config/
      linters:
        - forbidigo
      text: "os\\.Getenv"

    # Allow higher complexity in specific functions
    - linters:
        - gocyclo
      text: "(HandleFormSubmission|renderField|buildEmailBody|ValidateFields|validateChannel|CheckAndHandleIncident|UpdateForm|CreateForm|sendWebhook).*is high"

    - path: cmd/migrate/main\.go
      linters:
        - gocyclo

    # HTTP handlers - unused params are interface requirements
    - path: handlers/
      linters:
        - unparam
      text: "(w|r|ctx) is unused"
